# Generated by Django 3.1.7 on 2021-08-29 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Codes',
            new_name='Code',
        ),
    ]
