# Generated by Django 3.1.7 on 2021-08-31 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wapp', '0002_auto_20210829_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='language',
            field=models.CharField(default='', max_length=100),
        ),
    ]
