# Generated by Django 3.1.7 on 2021-08-31 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wapp', '0003_code_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='code',
            old_name='language',
            new_name='lang',
        ),
        migrations.AddField(
            model_name='code',
            name='lang_en',
            field=models.CharField(default='', max_length=100),
        ),
    ]
