# Generated by Django 3.1.7 on 2021-08-31 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wapp', '0004_auto_20210831_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='code',
            name='lang_en',
        ),
    ]
