# Generated by Django 3.1.7 on 2021-09-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_auto_20210914_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color1',
            field=models.CharField(default='black', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='color2',
            field=models.CharField(default='black', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='use',
            field=models.CharField(default='running', max_length=30),
        ),
    ]
