# Generated by Django 3.1.7 on 2021-09-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_auto_20210914_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(default='sneakers', max_length=30),
        ),
    ]
